#:kivy 1.8.0
<MyImage@Image>:
    source:'../res/emoji.png'
<MyGrid>:
    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Name: "

            TextInput:
                multinline:False

            Label:
                text: "Email: "

            TextInput:
                multiline:False

            MyImage:
        Button:
            text:"Submit"
            on_press: app.btn()